### ISSUE TITLE
Exception in thread "Thread-24" java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by Mann-Nariya** [JordanSamhi/AndroLog#2]
I was able to successfully generate the instrumented  file for an APK.apk file. The instrumentation process was successful and the logfile was successfully made capturing the logs from running the instrumented APK file installed on the device. 
The first two steps of AndroLog were successful. But when I tried to generate the report in the third step I came across some issues. 

I tried running the following command to generate a code coverage report of the app using the logfile and original apk.

<code>java -jar AndroLog-main/target/androlog-0.1-jar-with-dependencies.jar -p Android/Sdk/platforms -l MY_SUPER_LOG -a APK.apk -c -m -cp -s -pa APK_log  
</code>
But I got this error: 
<pre>[*] Setting up environment...
[✓] Done.
[*] Generating Code Coverage Report...
Exception in thread "Thread-24" java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.merge(HashMap.java:1393)
	at com.jordansamhi.androlog.SummaryBuilder.increment(SummaryBuilder.java:76)
	at com.jordansamhi.androlog.SummaryBuilder.incrementComponent(SummaryBuilder.java:87)
	at com.jordansamhi.androlog.SummaryBuilder.lambda$getInfoStatements$3(SummaryBuilder.java:179)
	at com.jordansamhi.androlog.SummaryBuilder$1.internalTransform(SummaryBuilder.java:65)
	at soot.BodyTransformer.transform(BodyTransformer.java:47)
	at soot.Transform.apply(Transform.java:126)
	at soot.BodyPack.internalApply(BodyPack.java:49)
	at soot.Pack.apply(Pack.java:126)
	at soot.PackManager.runBodyPacks(PackManager.java:992)
	at soot.PackManager.lambda$runBodyPacks$0(PackManager.java:667)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Exception in thread "main" java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.merge(HashMap.java:1393)
	at com.jordansamhi.androlog.SummaryBuilder.increment(SummaryBuilder.java:76)
	at com.jordansamhi.androlog.SummaryBuilder.incrementComponent(SummaryBuilder.java:87)
	at com.jordansamhi.androlog.SummaryBuilder.lambda$getInfoStatements$3(SummaryBuilder.java:179)
	at com.jordansamhi.androlog.SummaryBuilder$1.internalTransform(SummaryBuilder.java:65)
	at soot.BodyTransformer.transform(BodyTransformer.java:47)
	at soot.Transform.apply(Transform.java:126)
	at soot.BodyPack.internalApply(BodyPack.java:49)
	at soot.Pack.apply(Pack.java:126)
	at soot.PackManager.runBodyPacks(PackManager.java:992)
	at soot.PackManager.lambda$runBodyPacks$0(PackManager.java:667)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Exception in thread "Thread-17" java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.merge(HashMap.java:1393)
	at com.jordansamhi.androlog.SummaryBuilder.increment(SummaryBuilder.java:76)
	at com.jordansamhi.androlog.SummaryBuilder.incrementComponent(SummaryBuilder.java:87)
	at com.jordansamhi.androlog.SummaryBuilder.lambda$getInfoStatements$3(SummaryBuilder.java:179)
	at com.jordansamhi.androlog.SummaryBuilder$1.internalTransform(SummaryBuilder.java:65)
	at soot.BodyTransformer.transform(BodyTransformer.java:47)
	at soot.Transform.apply(Transform.java:126)
	at soot.BodyPack.internalApply(BodyPack.java:49)
	at soot.Pack.apply(Pack.java:126)
	at soot.PackManager.runBodyPacks(PackManager.java:992)
	at soot.PackManager.lambda$runBodyPacks$0(PackManager.java:667)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
</pre>
Many different log files are getting the same exception. 

Please take a look at this error.
Thank you for your time.

**Comment by JordanSamhi** [comment]
Hi @Mann-Nariya 

Could you please share one of these apps, I will try to find the problem.
Thanks !

**Comment by JordanSamhi** [comment]
@Mann-Nariya could you please share an app so that I investigate?

**Comment by Mann-Nariya** [comment]
APK Hashes: 
5F5BB0AAA811EE7D660C691EEF9FDE8D6DCA5003613A38DA6E359B455A0F0C2B
E51EB2C875BB44F8BB8D41BD5797FBF5CC005197C09ECDC2755E1788A2D75568

I executed the apps again for different time duration (e.g., 10, 20, and so on), stored the log files and tried generating the coverage reports for these APKs. The tool failed to generate coverage reports.

**Comment by JordanSamhi** [comment]
Hi @Mann-Nariya ,

So, I just tested the instrument, generated logs, and the report and did not encounter any issues; I was able to get the report.
Could you share your log file? Maybe it is related to specificity.

**Comment by Mann-Nariya** [comment]
Here is the log file. 

[5F5BB0AAA811EE7D660C691EEF9FDE8D6DCA5003613A38DA6E359B455A0F0C2B_log.txt](https://github.com/user-attachments/files/16125704/5F5BB0AAA811EE7D660C691EEF9FDE8D6DCA5003613A38DA6E359B455A0F0C2B_log.txt)

**Comment by JordanSamhi** [comment]
I was not able to reproduce the bug, I just tested with your log file and was able to generate the report :

<img width="584" alt="image" src="https://github.com/JordanSamhi/AndroLog/assets/35679728/b237e988-5880-482f-878e-fbae6814b642">

Are you using Java 8?

**Comment by Mann-Nariya** [comment]
This issue  also seems to be resolved after the recent commit. I am able to generate reports for the APKs I reported earlier. 

Thank you for your time.
